# use the predefined qt environment
Import('qtenv')

# apply uic to the form
qtenv.Uic4('CP2scope.ui')

# sources:
sources=Split("""
main.cpp
CP2Scope.cpp
PlotInfo.cpp
""")

# libraries:
libs = Split("""
cp2net
cp2lib
cp2config
QtCore
QtGui
QtNetwork
fftw3
fftw3_threads
scopeplot
knob
qwt
""")

# library paths:
libpaths=Split("""
../CP2Net
../CP2Lib
../CP2Config
../Moments
$QTDIR/lib
$QWTDIR/lib
$QTTOOLBOXDIR/ScopePlot
$QTTOOLBOXDIR/Knob
$FFTWDIR/lib
""")

# Build cp2scope
cp2scope = qtenv.Program('cp2scope', sources, LIBS=libs, LIBPATH=libpaths)

