/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT single_p3iq_d.cdb */

#define CHIP_6701 1

/*  Include Header Files  */
#include <std.h>
#include <hst.h>
#include <swi.h>
#include <tsk.h>
#include <log.h>
#include <sem.h>
#include <sts.h>

#ifdef __cplusplus
extern "C" {
#endif

extern far HST_Obj RTA_fromHost;
extern far HST_Obj RTA_toHost;
extern far SWI_Obj KNL_swi;
extern far TSK_Obj TSK_idle;
extern far TSK_Obj Init;
extern far TSK_Obj Data_send;
extern far TSK_Obj PCI_send;
extern far LOG_Obj LOG_system;
extern far SEM_Obj data_ready;
extern far SEM_Obj fifo_ready;
extern far SEM_Obj hwData_avail;
extern far SEM_Obj burst_ready;
extern far STS_Obj IDL_busyObj;
extern far void CSL_cfgInit();

#ifdef __cplusplus
}
#endif /* extern "C" */
