# use the predefined qt environment
Import('env')

# apply uic to the PPI form
env.Uic4('CP2PPI.ui')

# apply uic to the color bar settings form
env.Uic4('ColorBarSettings.ui')

# sources:
sources=Split("""
main.cpp
CP2PPI.cpp
PpiInfo.cpp
ColorBarSettings.cpp
""")

# libraries:
libs = Split("""
cp2net
cp2lib
cp2config
QtCore
QtGui
QtOpenGL
QtNetwork
ppi
colorbar
glut
""")

# library paths:
libpaths=Split("""
../CP2Net
../CP2Lib
../CP2Config
$QTDIR/lib
$QTTOOLBOXDIR/designer
$QTTOOLBOXDIR/lib
$GLUTDIR/lib
""")

# Build cp2ppi
cp2ppi = env.Program('cp2ppi', sources, LIBS=libs, LIBPATH=libpaths)

# install CP2PPI
env.InstallBin(cp2ppi)

