# use the predefined qt environment
Import('env')

# apply uic to the form
env.Uic4('CP2Sim.ui')

# sources:
sources=Split("""
main.cpp
CP2Sim.cpp
CP2SimThread.cpp
""")

# libraries:
libs = Split("""
cp2net
cp2lib
cp2config
QtCore
QtGui
QtNetwork
""")

# library paths:
libpaths=Split("""
../CP2Net
../CP2Lib
../CP2Config
$QTDIR/lib
""")

# Build cp2sim
cp2sim = env.Program('cp2sim', sources, LIBS=libs, LIBPATH=libpaths)

# install cp2sim
env.InstallBin(cp2sim)


